// Pure card-note text + frontmatter -> siblings. No Obsidian imports.
// A card note is one Markdown file: frontmatter metadata plus a body that is
// either a basic card (# Front / # Back sections) or a cloze card (==cN:…== highlights).

import { maskMarkdownCode, type MarkdownLine } from './markdown-code';

export type CardKind = 'basic' | 'cloze';

export interface ParsedSibling {
	/** Stable sibling index persisted in review events. */
	sub: number;
	/** Markdown shown before revealing the answer. */
	front: string;
	/** Markdown shown after revealing the answer. */
	back: string;
}

export interface ParsedCardNote {
	/** Frontmatter id, or null while the note is unstamped. */
	id: string | null;
	/** Effective kind: declared in frontmatter, or inferred from the body. Null for non-card notes. */
	kind: CardKind | null;
	/** Kind read from frontmatter; null when missing or invalid (adoption writes the inferred kind). */
	declaredKind: CardKind | null;
	/** User-authored persistent state from frontmatter. */
	suspended: boolean;
	reverse: boolean;
	/** Independently scheduled prompts generated by this note. Empty while the card is incomplete. */
	siblings: ParsedSibling[];
	/** 0-based editor line of the card's first content, for cursor placement. */
	line: number;
}

// Frontmatter keys are prefixed: Obsidian properties are a vault-wide namespace, and
// generic keys like "id"/"type" collide with users' own metadata on dropped-in notes.
export const ID_PROPERTY = 'remember-id';
export const TYPE_PROPERTY = 'remember-type';
export const REVERSE_PROPERTY = 'remember-reverse';
export const SUSPEND_PROPERTY = 'remember-suspend';

export const FRONT_HEADING = '# Front';
export const BACK_HEADING = '# Back';

const HEADING = /^#[ \t]+(front|back)[ \t]*$/i;
const CLOZE = /==c([1-9][0-9]*):(.*?)==/g;
const CLOZE_LIKE = /==c[0-9]*:/i;

interface ClozeMarker {
	number: number;
	line: number;
	start: number;
	end: number;
	answer: string;
}

export function parseCardNote(text: string, frontmatter: Record<string, unknown> | null | undefined): ParsedCardNote {
	const meta = {
		id: readCardId(frontmatter),
		declaredKind: readCardKind(frontmatter),
		suspended: frontmatter?.[SUSPEND_PROPERTY] === true,
		reverse: frontmatter?.[REVERSE_PROPERTY] === true,
	};
	const lines = maskMarkdownCode(text.split('\n').map(clean));
	const start = bodyStart(lines);
	const kind = meta.declaredKind ?? inferKind(lines, start);
	if (kind === null) {
		return { ...meta, kind: null, siblings: [], line: start };
	}
	const body =
		kind === 'basic' ? parseBasicBody(lines, start, meta.reverse) : parseClozeBody(lines, start);
	return { ...meta, kind, ...body };
}

/** The inferred kind of a body without declared frontmatter, or null for a non-card note. */
export function inferKind(lines: readonly MarkdownLine[], start = bodyStart(lines)): CardKind | null {
	for (let i = start; i < lines.length; i++) {
		if (headingName(lines[i]) === 'front') return 'basic';
	}
	for (let i = start; i < lines.length; i++) {
		if (CLOZE_LIKE.test(lines[i].searchable)) return 'cloze';
	}
	return null;
}

export function parseNoteLines(text: string): MarkdownLine[] {
	return maskMarkdownCode(text.split('\n').map(clean));
}

/** Frontmatter is metadata, never card text. */
export function bodyStart(lines: readonly MarkdownLine[]): number {
	if (lines[0]?.raw !== '---') return 0;
	for (let i = 1; i < lines.length; i++) {
		const line = lines[i].raw.trimEnd();
		if (line === '---' || line === '...') return i + 1;
	}
	return 0;
}

/** An incomplete card (missing or empty Front/Back section) has no siblings. */
function parseBasicBody(
	lines: readonly MarkdownLine[],
	start: number,
	reverse: boolean,
): Pick<ParsedCardNote, 'siblings' | 'line'> {
	const frontAt = findHeading(lines, start, 'front');
	if (frontAt < 0) return { siblings: [], line: start };
	const backAt = findHeading(lines, frontAt + 1, 'back');
	const front = sectionText(lines, frontAt + 1, (backAt < 0 ? lines.length : backAt) - 1);
	const line = firstContentLine(lines, frontAt + 1, (backAt < 0 ? lines.length : backAt) - 1) ?? frontAt;
	if (front === '' || backAt < 0) return { siblings: [], line };
	const back = sectionText(lines, backAt + 1, lines.length - 1);
	if (back === '') return { siblings: [], line };
	const siblings: ParsedSibling[] = [{ sub: 0, front, back }];
	if (reverse) siblings.push({ sub: 1, front: back, back: front });
	return { siblings, line };
}

/** A cloze without valid markers, or with broken marker syntax, has no siblings. */
function parseClozeBody(
	lines: readonly MarkdownLine[],
	start: number,
): Pick<ParsedCardNote, 'siblings' | 'line'> {
	const markers: ClozeMarker[] = [];
	let malformed = false;
	for (let i = start; i < lines.length; i++) {
		const { raw, searchable } = lines[i];
		let masked = searchable;
		CLOZE.lastIndex = 0;
		for (let match = CLOZE.exec(searchable); match !== null; match = CLOZE.exec(searchable)) {
			const number = Number(match[1]);
			const answerStart = match.index + `==c${match[1]}:`.length;
			const answerEnd = match.index + match[0].length - 2;
			const answer = raw.slice(answerStart, answerEnd);
			masked = masked.slice(0, match.index) + ' '.repeat(match[0].length) + masked.slice(match.index + match[0].length);
			if (!Number.isSafeInteger(number) || answer.trim() === '') {
				malformed = true;
				continue;
			}
			markers.push({ number, line: i, start: match.index, end: match.index + match[0].length, answer });
		}
		// A cloze-like fragment outside every valid marker is broken syntax, not card text.
		if (CLOZE_LIKE.test(masked)) malformed = true;
	}

	const line = markers[0]?.line ?? firstContentLine(lines, start, lines.length - 1) ?? start;
	if (malformed || markers.length === 0) return { siblings: [], line };

	const numbers = [...new Set(markers.map((marker) => marker.number))].sort((a, b) => a - b);
	return {
		siblings: numbers.map((number) => ({
			sub: number + 1,
			front: renderCloze(lines, start, markers, number),
			back: renderCloze(lines, start, markers, undefined, number),
		})),
		line,
	};
}

/**
 * The whole body with each marker replaced by its answer, or by […] when its number is hidden.
 * `revealed` marks the number being tested so the answer side can highlight what was hidden.
 */
function renderCloze(
	lines: readonly MarkdownLine[],
	start: number,
	markers: readonly ClozeMarker[],
	hidden?: number,
	revealed?: number,
): string {
	const rendered: string[] = [];
	for (let i = start; i < lines.length; i++) {
		const raw = lines[i].raw;
		const own = markers.filter((marker) => marker.line === i);
		let result = '';
		let cursor = 0;
		for (const marker of own) {
			result += raw.slice(cursor, marker.start);
			if (marker.number === hidden) result += '[…]';
			else if (marker.number === revealed) result += `==${marker.answer}==`;
			else result += marker.answer;
			cursor = marker.end;
		}
		rendered.push(result + raw.slice(cursor));
	}
	return trimBlankEdges(rendered).join('\n');
}

function findHeading(lines: readonly MarkdownLine[], from: number, name: 'front' | 'back'): number {
	for (let i = from; i < lines.length; i++) {
		if (headingName(lines[i]) === name) return i;
	}
	return -1;
}

function headingName(line: MarkdownLine): string | null {
	const match = HEADING.exec(line.searchable.trimEnd());
	return match ? match[1].toLowerCase() : null;
}

function sectionText(lines: readonly MarkdownLine[], from: number, to: number): string {
	const kept: string[] = [];
	for (let i = from; i <= to && i < lines.length; i++) kept.push(lines[i].raw);
	return trimBlankEdges(kept).join('\n');
}

function firstContentLine(lines: readonly MarkdownLine[], from: number, to: number): number | null {
	for (let i = from; i <= to && i < lines.length; i++) {
		if (lines[i].raw.trim() !== '') return i;
	}
	return null;
}

function trimBlankEdges(lines: string[]): string[] {
	let start = 0;
	let end = lines.length;
	while (start < end && lines[start].trim() === '') start++;
	while (end > start && lines[end - 1].trim() === '') end--;
	return lines.slice(start, end).map((line) => line.trimEnd());
}

/** Ids are opaque; strings and YAML-mangled numbers are accepted, anything unusable is re-minted. */
export function readCardId(frontmatter: Record<string, unknown> | null | undefined): string | null {
	const raw = frontmatter?.[ID_PROPERTY];
	if (typeof raw !== 'string' && typeof raw !== 'number') return null;
	const id = String(raw).trim();
	return id !== '' && !/[\s#]/.test(id) ? id : null;
}

export function readCardKind(frontmatter: Record<string, unknown> | null | undefined): CardKind | null {
	const raw = frontmatter?.[TYPE_PROPERTY];
	if (typeof raw !== 'string') return null;
	const kind = raw.trim().toLowerCase();
	return kind === 'basic' || kind === 'cloze' ? kind : null;
}

function clean(line: string | undefined): string {
	return (line ?? '').replace(/\r$/, '');
}
