// Pure note-text -> Card[] parsing. No Obsidian imports.

import { maskMarkdownCode, type MarkdownLine } from './markdown-code';

export interface ParsedSibling {
	/** Stable sibling index persisted in review events. */
	sub: number;
	/** Markdown shown before revealing the answer. */
	front: string;
	/** Markdown shown after revealing the answer. */
	back: string;
}

export interface ParsedCard {
	/** Identity token id, or null while the card is unstamped. */
	id: string | null;
	/** User-authored persistent state from a leading {suspend} marker. */
	suspended: boolean;
	kind: 'basic' | 'cloze';
	/** Independently scheduled prompts generated by this card group. */
	siblings: ParsedSibling[];
	/** Multi-line basic block vs single-line basic/cloze card. Decides where the id token goes. */
	multiline: boolean;
	/** 0-based first content line and stamp insertion point. */
	line: number;
}

export const TOKEN_PATTERN = '%%rem:[0-9a-z]+%%';
const TOKEN = new RegExp(TOKEN_PATTERN, 'g');
const TOKEN_ONLY = /^%%rem:([0-9a-z]+)%%$/;
const TOKEN_AT_END = /%%rem:([0-9a-z]+)%%\s*$/;
const CLOZE = /\{\{c([1-9][0-9]*)::(.*?)\}\}/g;
const CLOZE_LIKE = /\{\{c[0-9]*::/i;
const SUSPEND_PREFIX = /^(\s*)\{suspend\}(?:[ \t]+|$)/;

interface ClozeMarker {
	number: number;
	start: number;
	end: number;
	answer: string;
}

export function parseCards(text: string): ParsedCard[] {
	const lines = maskMarkdownCode(text.split('\n').map(clean));
	const start = bodyStart(lines);
	const isBlank = (i: number) => lines[i].raw.trim() === '';

	const cards: ParsedCard[] = [];
	let i = start;
	while (i < lines.length) {
		if (isBlank(i)) {
			i++;
			continue;
		}
		let end = i;
		while (end + 1 < lines.length && !isBlank(end + 1)) end++;
		parseBlock(lines, i, end, cards);
		i = end + 1;
	}
	return cards;
}

/** Frontmatter is metadata (it carries the deck property), never card text. */
function bodyStart(lines: readonly MarkdownLine[]): number {
	if (lines[0]?.raw !== '---') return 0;
	for (let i = 1; i < lines.length; i++) {
		const line = lines[i].raw.trimEnd();
		if (line === '---' || line === '...') return i + 1;
	}
	return 0;
}
/** A block is the contiguous run of non-blank lines [start, end]. */
function parseBlock(lines: readonly MarkdownLine[], start: number, end: number, out: ParsedCard[]): void {
	// A token on its own line directly above the block is the block's id (multi-line cards).
	const first = lines[start];
	const blockToken = first.raw.trim() === first.searchable.trim() ? TOKEN_ONLY.exec(first.raw.trim()) : null;
	const contentStart = blockToken ? start + 1 : start;

	let separator = -1;
	for (let i = contentStart; i <= end; i++) {
		const trimmed = lines[i].searchable.trim();
		if (trimmed === '?' || trimmed === '??') {
			separator = i;
			break;
		}
	}

	// A block with a ?/?? line is one multi-line card. Nothing inside it is parsed further.
	if (separator >= 0) {
		// Card types cannot be mixed. Code is already masked in searchable text.
		if (lines.slice(contentStart, end + 1).some((line) => CLOZE_LIKE.test(line.searchable))) return;
		const firstContent = withoutSuspendPrefix(lines[contentStart]);
		const front = blockText(lines, contentStart, separator - 1, firstContent.line);
		const back = blockText(lines, separator + 1, end);
		const reversed = lines[separator].searchable.trim() === '??';
		out.push({
			id: blockToken ? blockToken[1] : null,
			suspended: firstContent.suspended,
			kind: 'basic',
			siblings: basicSiblings(front, back, reversed),
			multiline: true,
			line: contentStart,
		});
		return;
	}

	// Otherwise every line may be one line-scoped cloze or basic card.
	for (let i = start; i <= end; i++) {
		const { raw, searchable } = lines[i];
		const endToken = tokenAtEnd(raw, searchable);
		const status = withoutSuspendPrefix({ raw, searchable });
		const source = withoutTokens(status.line.raw, status.line.searchable);
		const cloze = parseClozeLine(source.raw, source.searchable);
		if (cloze !== null) {
			if (cloze.length > 0) {
				out.push({
					id: endToken ? endToken[1] : null,
					suspended: status.suspended,
					kind: 'cloze',
					siblings: cloze,
					multiline: false,
					line: i,
				});
			}
			continue;
		}
		// Separators are checked longest-first: ::: before ::.
		const at3 = source.searchable.indexOf(':::');
		const at = at3 >= 0 ? at3 : source.searchable.indexOf('::');
		if (at < 0) continue;
		const width = at3 >= 0 ? 3 : 2;
		const front = source.raw.slice(0, at).trim();
		const back = source.raw.slice(at + width).trim();
		out.push({
			id: endToken ? endToken[1] : null,
			suspended: status.suspended,
			kind: 'basic',
			siblings: basicSiblings(front, back, width === 3),
			multiline: false,
			line: i,
		});
	}
}

function basicSiblings(front: string, back: string, reversed: boolean): ParsedSibling[] {
	const siblings: ParsedSibling[] = [{ sub: 0, front, back }];
	if (reversed) siblings.push({ sub: 1, front: back, back: front });
	return siblings;
}

/** Returns null for a non-cloze line, [] for malformed/mixed syntax, or its cloze siblings. */
function parseClozeLine(raw: string, searchable: string): ParsedSibling[] | null {
	const markers: ClozeMarker[] = [];
	CLOZE.lastIndex = 0;
	for (let match = CLOZE.exec(searchable); match !== null; match = CLOZE.exec(searchable)) {
		const number = Number(match[1]);
		const answerStart = match.index + `{{c${match[1]}::`.length;
		const answerEnd = match.index + match[0].length - 2;
		const answer = raw.slice(answerStart, answerEnd);
		if (
			!Number.isSafeInteger(number) ||
			number < 1 ||
			number >= Number.MAX_SAFE_INTEGER ||
			answer.trim() === '' ||
			answer.includes('{{') ||
			answer.includes('::')
		) {
			return [];
		}
		markers.push({ number, start: match.index, end: match.index + match[0].length, answer });
	}

	if (markers.length === 0) return CLOZE_LIKE.test(searchable) ? [] : null;
	const outside = maskRanges(searchable, markers);
	if (CLOZE_LIKE.test(outside) || outside.includes('::')) return [];

	const revealed = renderCloze(raw, markers);
	const numbers = [...new Set(markers.map((marker) => marker.number))].sort((a, b) => a - b);
	return numbers.map((number) => ({
		sub: number + 1,
		front: renderCloze(raw, markers, number),
		back: revealed,
	}));
}

function renderCloze(raw: string, markers: readonly ClozeMarker[], hidden?: number): string {
	let result = '';
	let start = 0;
	for (const marker of markers) {
		result += raw.slice(start, marker.start);
		result += marker.number === hidden ? '[…]' : marker.answer;
		start = marker.end;
	}
	return (result + raw.slice(start)).trimEnd();
}

function maskRanges(text: string, markers: readonly ClozeMarker[]): string {
	let result = '';
	let start = 0;
	for (const marker of markers) {
		result += text.slice(start, marker.start) + ' '.repeat(marker.end - marker.start);
		start = marker.end;
	}
	return result + text.slice(start);
}

function withoutTokens(raw: string, searchable: string): MarkdownLine {
	return {
		raw: stripTokens(raw, searchable),
		searchable: stripTokens(searchable, searchable),
	};
}

function blockText(
	lines: readonly MarkdownLine[],
	from: number,
	to: number,
	firstLine: MarkdownLine | undefined = lines[from],
): string {
	const kept: string[] = [];
	for (let i = from; i <= to; i++) {
		const { raw, searchable } = i === from ? firstLine : lines[i];
		if (raw.trim() === searchable.trim() && TOKEN_ONLY.test(raw.trim())) continue;
		kept.push(stripTokens(raw, searchable));
	}
	return kept.join('\n');
}

function withoutSuspendPrefix(line: MarkdownLine): { line: MarkdownLine; suspended: boolean } {
	const match = SUSPEND_PREFIX.exec(line.searchable);
	if (!match) return { line, suspended: false };
	const leading = match[1];
	return {
		line: {
			raw: leading + line.raw.slice(match[0].length),
			searchable: leading + line.searchable.slice(match[0].length),
		},
		suspended: true,
	};
}

function tokenAtEnd(raw: string, searchable: string): RegExpExecArray | null {
	const match = TOKEN_AT_END.exec(raw);
	if (match === null) return null;
	const token = `%%rem:${match[1]}%%`;
	return searchable.slice(match.index, match.index + token.length) === token ? match : null;
}

function stripTokens(raw: string, searchable: string): string {
	let result = '';
	let start = 0;
	TOKEN.lastIndex = 0;
	for (let match = TOKEN.exec(searchable); match !== null; match = TOKEN.exec(searchable)) {
		result += raw.slice(start, match.index);
		start = match.index + match[0].length;
	}
	return result + raw.slice(start);
}

function clean(line: string | undefined): string {
	return (line ?? '').replace(/\r$/, '');
}
